services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25 # Or your preferred version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=123123  # Set the password here
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.25 # Same version as Elasticsearch
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://localhost:9200"
    networks:
      - elastic

volumes:
  es_data:

networks:
  elastic: